### ISSUE TITLE
i dont get it how do i export from yomichan on chrome

### ISSUE THREAD

**Issue by Triramama** [themoeway/yomichan-data-exporter#4]
following instructions i pasted the code in console and ??? nothing happening please help

**Comment by MarvNC** [comment]
Hi there,

Thank you for reaching out. To better assist you with exporting from Yomichan on Chrome, could you please provide more details? Specifically:

1. Which instructions are you following? Could you share a link or describe the steps?
2. What code did you paste into the console?
3. Are there any error messages or logs appearing in the console?
4. What version of Chrome and Yomichan are you using?

This information will help us diagnose the issue more effectively. Thanks!
